###############################################################################
# Конфигурация агента Password Sync
###############################################################################

CENTRAL_SERVER="password-sync-center"

SSH_USER="vadmin"

SSH_TIMEOUT=10

RETRY_DELAY=60
