###############################################################################
# Маршрутизация пользователей
#
# Формат:
#
# пользователь=группа_ansible
###############################################################################

admin=all
user2=web
user3=kuma
postgres=db
